### ISSUE TITLE
Tratamento de exceção - Buscar cliente por id

### ISSUE THREAD

**Issue by oliveiralex** [dansaraiva/tarefa01-bootcamp#1]
Caro Daniel,

Meu nome é Alexandre e eu estou corrigindo o seu trabalho. 

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor corrigir a exceção lançada na busca por id. Deveria ser ResourceNotFoundException e não EntityNotFoundException. Está retornando erro 500. 

Peço que assim que possível você realize a adequação.

Abraço

**Comment by dansaraiva** [comment]
Olá!!!

Correção efetuada!
Agradeço o feedback.

**Comment by oliveiralex** [comment]
Obrigado Daniel!
